language: python

stages:
  - ci
  - release

jobs:
  include:

    - stage: ci
      python: "2.7"
      name: ci-py27

    - stage: ci
      python: "3.6"
      name: ci-py36

    - stage: ci
      python: "3.7"
      dist: xenial  # Need for python 3.7
      name: ci-py37

    - stage: release
      python: "3.7"
      dist: xenial  # Need for python 3.7
      name: release
      script: |

        curl -f -L https://github.com/iliapolo/pyci/releases/download/0.5.2/py-ci-$(uname -m)-$(uname -s) -o pyci
        chmod +x pyci
        ./pyci pack --path . binary --name q --entrypoint bin/q

install: pip install -r requirements.txt
before_script: flake8 ./bin/q ./test/test-suite --count --select=E901,E999,F821,F822,F823 --show-source --statistics
script: test/test-all
